#spring.application.name=Portfolio_Mgmt_Trial
spring.application.name=dumb-money-tracker
server.port=8080

# API Keys
alphavantage.api.key=AZ44WXK4AEUJD2TB
spring.ai.openai.api-key=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

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=n3u3da!
spring.jpa.hibernate.ddl-auto=update
spring.main.web-application-type=servlet